markdown:         kramdown

permalink:        /post/:categories/:year/:month/:day/:title/

title:            'tmpfs /home/stan'
description:      'Stan Angeloff’s blog, a collection of thoughts, rants & research'
url:              https://blog.angeloff.name
baseurl:          ''

author:
  name:           'Stan Angeloff'
  url:            https://blog.angeloff.name

paginate:         5
paginate_path:    '/page,:num/'

excerpt_separator: '<!-- excerpt -->'

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

include:
  - favicon.ico
  - keybase.txt
  - robots.txt

github:
  user:           StanAngeloff

twitter:
  username:       StanAngeloff
  card:           summary

keybase:
  user:           StanAngeloff
