safe:      false
lsi:       false
pygments:  true
paginate:  10
permalink: date
markdown:  redcarpet
redcarpet:
  extensions: [
    "autolink",
    "fenced_code",
    "hard_wrap",
    "lax_htmlblock",
    "no_intraemphasis",
    "space_header",
    "strikethrough",
    "tables"
  ]
