base:       http://blog.angeloff.name
title:      Stan Angeloff’s blog

safe:       false
lsi:        false
pygments:   true
permalink:  /post/:categories/:year/:month/:day/:title/
markdown:   redcarpet
include:    [
  "robots.txt",
  "rss.xml",
  "sitemap.xml"
]

redcarpet:
  extensions: [
    "autolink",
    "fenced_code",
    "hard_wrap",
    "lax_htmlblock",
    "no_intraemphasis",
    "space_header",
    "strikethrough",
    "tables"
  ]
