import { execFile } from "node:child_process";
import { promisify } from "node:util";
import fs from "node:fs/promises";
import path from "node:path";

/** Dev-only middleware: GET /__mastodon-summary?id=<post-id> returns
 *  { summary } — a ≤280-char toot body generated by the Anthropic API.
 *  Registered via astro:server:setup, so it exists only under `astro dev`
 *  and leaves no trace in the static build. */

const MODEL = "claude-sonnet-4-6";
const MAX_SUMMARY_CHARS = 280;
const POSTS_DIR = path.resolve("src/content/posts");
const TONE_GUIDE = path.resolve("contrib/llms/2026-05-15-tone.md");

const execFileAsync = promisify(execFile);

let cachedApiKey = null;

function httpError(status, message) {
  const error = new Error(message);
  error.httpStatus = status;
  return error;
}

async function resolveApiKey() {
  if (cachedApiKey) return cachedApiKey;
  if (process.env.ANTHROPIC_API_KEY) {
    cachedApiKey = process.env.ANTHROPIC_API_KEY;
    return cachedApiKey;
  }
  try {
    const { stdout } = await execFileAsync("secret-tool", [
      "lookup",
      "service",
      "anthropic",
      "key",
      "api",
    ]);
    const key = stdout.trim();
    if (key) {
      cachedApiKey = key;
      return key;
    }
  } catch {
    // fall through to the error below
  }
  throw httpError(
    500,
    "No Anthropic API key. Set ANTHROPIC_API_KEY, or store one with: " +
      "secret-tool store --label=Anthropic service anthropic key api",
  );
}

async function readPostBody(id) {
  if (!/^[A-Za-z0-9._-]+$/.test(id)) {
    throw httpError(400, "Invalid or missing post id");
  }
  for (const ext of [".md", ".mdx"]) {
    const filePath = path.resolve(POSTS_DIR, id + ext);
    if (!filePath.startsWith(POSTS_DIR + path.sep)) continue;
    try {
      const raw = await fs.readFile(filePath, "utf-8");
      return raw.replace(/^---[\s\S]*?---\s*/, "");
    } catch {
      // try the next extension
    }
  }
  throw httpError(404, `Post not found: ${id}`);
}

async function buildSystemPrompt() {
  let prompt = `You write short Mastodon posts announcing Stan Angeloff's blog posts.

Rules:
- At most ${MAX_SUMMARY_CHARS} characters.
- First person, as Stan.
- British English, no Oxford comma, em-dashes spaced like " — ".
- No hashtags, no emoji, no links (the post URL is appended separately).
- Don't repeat the title verbatim; say what the reader gets out of it.
- Output only the post text, nothing else.`;
  try {
    const tone = await fs.readFile(TONE_GUIDE, "utf-8");
    prompt += `\n\nStan's general style guide, for voice reference:\n\n${tone}`;
  } catch {
    // tone guide is optional
  }
  return prompt;
}

async function generateSummary(body) {
  const { default: Anthropic } = await import("@anthropic-ai/sdk");
  const client = new Anthropic({ apiKey: await resolveApiKey() });
  let response;
  try {
    response = await client.messages.create({
      model: MODEL,
      max_tokens: 1024,
      system: await buildSystemPrompt(),
      messages: [
        {
          role: "user",
          content: `Write the Mastodon post for this blog post:\n\n${body}`,
        },
      ],
    });
  } catch (error) {
    if (error instanceof Anthropic.APIError) {
      throw httpError(502, `Anthropic API: ${error.message}`);
    }
    throw error;
  }
  const text = response.content
    .filter((block) => block.type === "text")
    .map((block) => block.text)
    .join("")
    .trim();
  if (!text) throw httpError(502, "Model returned an empty summary");
  return text;
}

export default function mastodonSummary() {
  return {
    name: "mastodon-summary",
    hooks: {
      "astro:server:setup": ({ server }) => {
        server.middlewares.use("/__mastodon-summary", (req, res) => {
          // Connect strips the mount path, leaving e.g. "/?id=...".
          const url = new URL(req.url, "http://localhost");
          const id = url.searchParams.get("id") || "";
          readPostBody(id)
            .then(generateSummary)
            .then(
              (summary) => {
                res.setHeader("Content-Type", "application/json");
                res.end(JSON.stringify({ summary }));
              },
              (error) => {
                res.statusCode = error.httpStatus || 500;
                res.setHeader("Content-Type", "application/json");
                res.end(JSON.stringify({ error: error.message }));
              },
            );
        });
      },
    },
  };
}
